### ISSUE TITLE
...

### ISSUE THREAD

**Issue by pol2095** [dandar3/android-google-play-services-base#2]
...

**Comment by dandar3** [comment]
I see you resolved your issue, but just in case someone else will stumble onto it.

Launch Android [SDK Manager](https://developer.android.com/studio/intro/update.html) (`SDK Manager.exe` on Windows) scroll down to `Extra` and install `Google Repository`.

If you hover the entries in the SDK Manager you will get in the tooltips the location of a particular package before installing.
