### ISSUE TITLE
Cannot find Leader board and Achievement features 

### ISSUE THREAD

**Issue by hiendvmobgame** [dandar3/android-google-play-services-base#3]
Hi!
First of all, I would like to send you the deepest thanks to you for creating this library. It's really very helpful to me.!
Also I have a question for you. Why this does not contains Leaderboard and Achievement features.
Best regards!

**Comment by dandar3** [comment]
@hiendvmobgame 
You're quite welcome!

I believe Leaderboard and Achievement features are part of Google Play Games Services ([android-google-play-services-games](https://github.com/dandar3/android-google-play-services-games/)).

Best to star the [android-google-play-services-README](https://github.com/dandar3/android-google-play-services-README) project for a better overview. Also see the two videos at the end of the README.md that should show you an easier way to import an entire project set with all necessary dependencies.
